export const courseTitles: string[] = [
  "HYDROGEN SULPHIDE AWARENESS (H2S)",
  "HELICOPTER UNDERWATER ESCAPE TRAINING (HUET)",
  "BASIC OFFSHORE SAFETY EDUCATION AND EMERGENCY TRAINING (BOSET)",
  "RIGGING AND SLINGING SAFETY LEVEL 2",
  "LIFTING AND HOISTING SAFETY",
  "CRANE OPERATIONS THEORY (PRACTICAL ON DEMAND)",
  "COOKERY COURSE WITH HACCP",
  "BASIC COOKING COURSE CERTIFICATION",
  "PSD CROWD MANAGEMENT",
  "PSD HUMAN BEHAVIOUR",
  "HOSPITALITY & SPANISH COURSE",
  "SHIP BOARD SAFETY & SECURITY (SOFF)",
  "SECURITY FACILITY CODE & AWARENESS",
  "SHIPPING NEW ENTRY FOR FITTER & WELDERS",
  "SHIPPING NEW ENTRY TO MECHANICAL & REFRIGERATION TECHNICIANS",
  "ELECTRICAL & ELECTRONIC TECHNICIANS BRIDGING COURSE",
  // Short term safety value added courses
  "MARINE ENGLISH",
  "BASIC FIRE PREVENTION",
  "PERSONAL SURVIVAL TECHNIQUES",
  "ELEMENTARY FIRST AID",
  "PERSONAL SAFETY & SOCIAL RESPONSIBILITIES",
  "SECURITY AWARENESS",
  "CARGO HANDLING SAFETY",
]

export default courseTitles
